name = "cloudfare-d1-nextauth-prisma"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Add the binding for your D1 database here
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cloudfare-d1-nextauth-prisma"
database_id = "a6560e8a-744e-48e5-bb1d-79b76a2b48ff"
